services:
  api:
    build: ./Bank.Api
    container_name: bank_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=bankdb;Username=bank;Password=bank123
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: bank_pg
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank123
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: